[client]

# Controls whether uncaught app exceptions and deprecation warnings
# are displayed in the browser. By default, this is set to True and
# Streamlit displays app exceptions and associated tracebacks, and
# deprecation warnings, in the browser.

# If set to False, deprecation warnings and full exception messages
# will print to the console only. Exceptions will still display in the
# browser with a generic error message. For now, the exception type and
# traceback show in the browser also, but they will be removed in the
# future.

# Default: true PRODUCTION SET FALSE
showErrorDetails = false

# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).

# Allowed values:
# * "auto" : Show the developer options if the app is accessed through
# localhost or through Streamlit Community Cloud as a developer.
# Hide them otherwise.
# * "developer" : Show the developer options.
# * "viewer" : Hide the developer options.
# * "minimal" : Show only options set externally (e.g. through
# Streamlit Community Cloud) or through st.set_page_config.
# If there are no options left, hide the menu.

# Default: "auto" PRODUCTION SET viewer/minimal
toolbarMode = "minimal"

# Controls whether the default sidebar page navigation in a multi-page app is displayed.

# Default: true
showSidebarNavigation = true

[server]
port=8501 # change port number. By default streamlit uses 8501 port
headless=true # This will eliminate automatically open browser
enableCORS=true 
enableXsrfProtection=true 
enableWebsocketCompression=false
maxUploadSize = 10

[browser] # This ip and port will show in command prompt
serverAddress = "localhost" # Put your Local IP or Domain Name
serverPort = 8501

[runner]
fastReruns = false

[theme]

primaryColor = "#1d959b"
font = "'Inter':https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
baseFontSize = 14
baseRadius = "8.0px"
buttonRadius = "8.0px"
borderColor = "#c4dae5"
dataframeHeaderBackgroundColor = "#eef0f5"
showWidgetBorder = true

[theme.sidebar]

primaryColor = "#1d959b"
secondaryBackgroundColor = "#f0f2f6"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
backgroundColor = "#eef0f5"