name: Create Release on New Tg

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on push events for tags like v1.0.0, v2.0.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ReadStore Basic ${{ github.ref_name }}
          body: |
            ReadStore Basic ${{ github.ref_name }}.

            README
            [README.md](https://github.com/JonathanAlles/readstore-basic/blob/main/docs/README.md)

            Changelog
            [CHANGELOG.md](https://github.com/JonathanAlles/readstore-basic/blob/main/CHANGELOG.md)

          draft: false
          prerelease: false
